// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZBHtPknUYAp5nJLZNbktaJuLs4p9pqY',
    appId: '1:352256142433:web:47772c1ecf8df15e354e20',
    messagingSenderId: '352256142433',
    projectId: 'test-app-with-di',
    authDomain: 'test-app-with-di.firebaseapp.com',
    storageBucket: 'test-app-with-di.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZBHtPknUYAp5nJLZNbktaJuLs4p9pqY',
    appId: '1:352256142433:android:9b25c5d216a7646e354e20',
    messagingSenderId: '352256142433',
    projectId: 'test-app-with-di',
    storageBucket: 'test-app-with-di.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4w9cARzi4jbkF6HD_zIpVletLmkO9RY',
    appId: '1:352256142433:ios:422ed5c2d5031fe6354e20',
    messagingSenderId: '352256142433',
    projectId: 'test-app-with-di',
    storageBucket: 'test-app-with-di.appspot.com',
    androidClientId: '352256142433-38h16aooveqs9bns876suv298stkgsod.apps.googleusercontent.com',
    iosClientId: '352256142433-ffsbu1hc66ofoqdqgo5ofjhik6dj55rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristApp',
  );
}
